import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

import { classifyOperations } from "./lib/classification.ts";
import type { OperationsManifest } from "./lib/census.ts";
import { countCensus } from "./lib/census.ts";
import type {
  OpenAPIDocument,
  ParameterObject,
  RequestBodyObject,
  ResponseObject,
  SchemaObject,
} from "./lib/openapi-document.ts";
import {
  collectParameters,
  deref,
  isReferenceObject,
  listOperations,
  successStatusCodes,
} from "./lib/openapi-document.ts";
import {
  loadClassificationRules,
  loadOperationsOverrides,
  type ClassificationRules,
  type OperationOverride,
} from "./lib/overrides.ts";
import { ZodEmitter } from "./lib/zod-emitter.ts";
import { assignToolNames, type AbbreviationRecord } from "./naming.ts";

export const GENERATOR_ID = "deterministic-zod-emitter";
export const GENERATOR_LOCK =
  "openapi-typescript@7 + scripts/lib/zod-emitter.ts (Orval Zod client skipped: no clean fixture schemas)";

const GENERATED_TS_HEADER = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate.ts using ${GENERATOR_ID}.
 * ${GENERATOR_LOCK}
 */

`;

const GENERATED_DTS_HEADER = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate.ts via openapi-typescript.
 */

`;

export interface GenerateOptions {
  specPath: string;
  outDir: string;
  openapiSha256?: string;
  classificationRulesPath?: string;
  operationsOverridesPath?: string;
  classificationRules?: ClassificationRules;
  operationsOverrides?: Record<string, OperationOverride>;
}

export interface GenerateResult {
  openapiSha256: string;
  manifest: OperationsManifest;
  abbreviations: AbbreviationRecord[];
  files: string[];
}

function repoRoot(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
}

export function sha256Hex(content: string | Buffer): string {
  return createHash("sha256").update(content).digest("hex");
}

function mediaSchema(
  content: Record<string, { schema?: SchemaObject | { $ref: string } }> | undefined,
  preferred: string[],
): { mediaType: string | undefined; schema: SchemaObject | { $ref: string } | undefined } {
  if (!content) {
    return { mediaType: undefined, schema: undefined };
  }
  for (const mediaType of preferred) {
    if (content[mediaType]?.schema) {
      return { mediaType, schema: content[mediaType]!.schema };
    }
  }
  const first = Object.entries(content)[0];
  if (!first) {
    return { mediaType: undefined, schema: undefined };
  }
  return { mediaType: first[0], schema: first[1]?.schema };
}

function parameterObjectShape(
  emitter: ZodEmitter,
  parameters: ParameterObject[],
  location: "path" | "query",
): string | undefined {
  const selected = parameters.filter((parameter) => parameter.in === location);
  if (selected.length === 0) {
    return undefined;
  }
  const lines = selected.map((parameter) => {
    const schemaExpr = emitter.emit(parameter.schema, "z.unknown()");
    const required = location === "path" ? true : parameter.required === true;
    const value = required ? schemaExpr : `${schemaExpr}.optional()`;
    const key = /^[A-Za-z_][A-Za-z0-9_]*$/.test(parameter.name)
      ? parameter.name
      : JSON.stringify(parameter.name);
    return `    ${key}: ${value}`;
  });
  return `z.object({\n${lines.join(",\n")}\n  })`;
}

function requestBodySchema(
  document: OpenAPIDocument,
  emitter: ZodEmitter,
  requestBody: RequestBodyObject | { $ref: string } | undefined,
): { expr: string | undefined; required: boolean; empty: boolean } {
  if (!requestBody) {
    return { expr: undefined, required: false, empty: false };
  }
  const resolved = deref<RequestBodyObject>(document, requestBody);
  const { mediaType, schema } = mediaSchema(resolved.content, [
    "application/json",
    "application/octet-stream",
    "multipart/form-data",
  ]);
  if (!schema) {
    return { expr: emitter.emitEmptyBody(), required: resolved.required === true, empty: true };
  }
  if (isReferenceObject(schema)) {
    return {
      expr: emitter.emit(schema, "z.unknown()"),
      required: resolved.required === true,
      empty: false,
    };
  }
  const propertyCount = schema.properties ? Object.keys(schema.properties).length : 0;
  const empty =
    mediaType === "application/json" &&
    (schema.type === "object" || schema.type === undefined) &&
    propertyCount === 0 &&
    !schema.allOf &&
    !schema.oneOf &&
    !schema.anyOf &&
    !schema.items;
  const expr = empty ? emitter.emitEmptyBody() : emitter.emit(schema, "z.unknown()");
  return { expr, required: resolved.required === true, empty };
}

function outputSchemaExpression(
  document: OpenAPIDocument,
  emitter: ZodEmitter,
  responses: Record<string, ResponseObject | { $ref: string }> | undefined,
): string {
  const statuses = successStatusCodes(responses);
  if (statuses.length === 0) {
    return "z.unknown()";
  }

  const expressions: string[] = [];
  for (const status of statuses) {
    const response = deref<ResponseObject>(document, responses![status]!);
    if (status === "204" || !response.content || Object.keys(response.content).length === 0) {
      expressions.push(`z.object({ success: z.literal(true), status: z.literal(204) })`);
      continue;
    }
    if (response.content["application/octet-stream"]) {
      expressions.push(
        `z.object({ contentType: z.string(), base64: z.string(), truncated: z.boolean() })`,
      );
      continue;
    }
    const { schema } = mediaSchema(response.content, ["application/json"]);
    if (!schema) {
      expressions.push("z.unknown()");
      continue;
    }
    expressions.push(emitter.emit(schema, "z.unknown()"));
  }

  const unique = [...new Set(expressions)];
  if (unique.length === 1) {
    return unique[0]!;
  }
  return `z.union([${unique.join(", ")}])`;
}

function safeExportName(operationId: string, suffix: string): string {
  const base = operationId.replace(/[^A-Za-z0-9_]/g, "_");
  const prefixed = /^[A-Za-z_]/.test(base) ? base : `_${base}`;
  return `${prefixed}${suffix}`;
}

function emitToolSchemas(document: OpenAPIDocument, operations = listOperations(document)): string {
  const emitter = new ZodEmitter(document);
  const chunks: string[] = [
    GENERATED_TS_HEADER,
    `import { z } from "zod";\n`,
    `export const generatorId = ${JSON.stringify(GENERATOR_ID)} as const;\n`,
  ];

  const registryEntries: string[] = [];

  for (const resolved of operations) {
    const parameters = collectParameters(document, resolved.pathItem, resolved.operation);
    const pathShape = parameterObjectShape(emitter, parameters, "path");
    const queryShape = parameterObjectShape(emitter, parameters, "query");
    const body = requestBodySchema(document, emitter, resolved.operation.requestBody);

    const inputFields: string[] = [];
    if (pathShape) {
      inputFields.push(`  path: ${pathShape}`);
    }
    if (queryShape) {
      inputFields.push(`  query: ${queryShape}`);
    }
    if (body.expr) {
      const bodyExpr = body.required ? body.expr : `${body.expr}.optional()`;
      inputFields.push(`  body: ${bodyExpr}`);
    }

    const inputName = safeExportName(resolved.operationId, "InputSchema");
    const outputName = safeExportName(resolved.operationId, "OutputSchema");
    const inputExpr =
      inputFields.length > 0 ? `z.object({\n${inputFields.join(",\n")}\n})` : "z.object({})";
    const outputExpr = outputSchemaExpression(document, emitter, resolved.operation.responses);

    chunks.push(`export const ${inputName} = ${inputExpr};\n`);
    chunks.push(`export const ${outputName} = ${outputExpr};\n`);
    registryEntries.push(
      `  ${JSON.stringify(resolved.operationId)}: { input: ${inputName}, output: ${outputName} }`,
    );
  }

  chunks.push(`export const toolSchemas = {\n${registryEntries.join(",\n")}\n} as const;\n`);
  chunks.push(`export type ToolSchemas = typeof toolSchemas;\n`);
  return `${chunks.join("\n")}`;
}

export async function buildManifest(
  document: OpenAPIDocument,
  openapiSha256: string,
  options: {
    classificationRules?: ClassificationRules;
    operationsOverrides?: Record<string, OperationOverride>;
    classificationRulesPath?: string;
    operationsOverridesPath?: string;
  } = {},
): Promise<{ manifest: OperationsManifest; abbreviations: AbbreviationRecord[] }> {
  const operations = listOperations(document);
  const rules =
    options.classificationRules ?? (await loadClassificationRules(options.classificationRulesPath));
  const overridesFile =
    options.operationsOverrides !== undefined
      ? { operations: options.operationsOverrides }
      : await loadOperationsOverrides(options.operationsOverridesPath);

  const naming = assignToolNames(operations.map((operation) => operation.operationId));
  const classified = classifyOperations({
    document,
    operations,
    rules,
    overrides: overridesFile.operations,
    toolNames: naming.toolNames,
  });

  return {
    manifest: {
      openapiSha256,
      census: countCensus(classified.records),
      operations: classified.records,
    },
    abbreviations: naming.abbreviations,
  };
}

export async function generateFromSpec(options: GenerateOptions): Promise<GenerateResult> {
  const absoluteSpecPath = path.resolve(options.specPath);
  const outDir = path.resolve(options.outDir);
  const raw = await readFile(absoluteSpecPath);
  const openapiSha256 = options.openapiSha256 ?? sha256Hex(raw);
  const document = JSON.parse(raw.toString("utf8")) as OpenAPIDocument;

  await mkdir(outDir, { recursive: true });

  const ast = await openapiTS(new URL(`file://${absoluteSpecPath}`));
  const openapiDts = `${GENERATED_DTS_HEADER}${astToString(ast)}`;
  const openapiDtsPath = path.join(outDir, "openapi.d.ts");
  await writeFile(openapiDtsPath, openapiDts, "utf8");

  const operations = listOperations(document);
  const toolSchemas = emitToolSchemas(document, operations);
  const toolSchemasPath = path.join(outDir, "tool-schemas.ts");
  await writeFile(toolSchemasPath, toolSchemas, "utf8");

  const manifestOptions: {
    classificationRules?: ClassificationRules;
    operationsOverrides?: Record<string, OperationOverride>;
    classificationRulesPath?: string;
    operationsOverridesPath?: string;
  } = {};
  if (options.classificationRules !== undefined) {
    manifestOptions.classificationRules = options.classificationRules;
  }
  if (options.operationsOverrides !== undefined) {
    manifestOptions.operationsOverrides = options.operationsOverrides;
  }
  if (options.classificationRulesPath !== undefined) {
    manifestOptions.classificationRulesPath = options.classificationRulesPath;
  }
  if (options.operationsOverridesPath !== undefined) {
    manifestOptions.operationsOverridesPath = options.operationsOverridesPath;
  }
  const { manifest, abbreviations } = await buildManifest(document, openapiSha256, manifestOptions);
  const manifestPath = path.join(outDir, "operations.manifest.json");
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

  const abbreviationsPath = path.join(outDir, "tool-name-abbreviations.json");
  await writeFile(abbreviationsPath, `${JSON.stringify(abbreviations, null, 2)}\n`, "utf8");

  return {
    openapiSha256,
    manifest,
    abbreviations,
    files: [openapiDtsPath, toolSchemasPath, manifestPath, abbreviationsPath],
  };
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const specIndex = args.indexOf("--spec");
  const outIndex = args.indexOf("--out");
  if (specIndex === -1 || !args[specIndex + 1]) {
    throw new Error("Usage: tsx scripts/generate.ts --spec <path> [--out <dir>]");
  }
  const root = repoRoot();
  const result = await generateFromSpec({
    specPath: args[specIndex + 1]!,
    outDir: outIndex === -1 ? path.join(root, "src/generated") : args[outIndex + 1]!,
  });
  process.stdout.write(
    `Generated ${result.files.length} files (sha256=${result.openapiSha256}, census=${result.manifest.census.total}/${result.manifest.census.get}/${result.manifest.census.nonGet})\n`,
  );
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
